use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Default)]
pub struct AnaggeliesE3Wrapper{
    #[serde(rename = "AnaggeliesE3")]
    pub anaggelies: AnaggeliesE3

}

#[derive(Serialize, Deserialize, Debug, Default)]
pub struct AnaggeliesE3{
    #[serde(rename = "AnaggeliaE3")]
    pub anaggelia: Vec<AnaggeliaE3>,
}

#[derive(Serialize, Deserialize, Debug, Default)]
pub struct AnaggeliaE3{
    pub f_aa_pararthmatos: String,
    pub f_rel_protocol: String ,
    pub f_rel_date: String,
    pub f_ypiresia_sepe: String,
    pub f_ypiresia_oaed: String,
    pub f_ergodotikh_organwsh: String,
    pub f_kad_kyria: String,
    pub f_kad_deyt_1: String,
    pub f_kad_deyt_2: String,
    pub f_kad_deyt_3: String,
    pub f_kad_deyt_4: String,
    pub f_kad_pararthmatos: String,
    pub f_kallikratis_pararthmatos: String,
    pub f_eponymo: String,
    pub f_onoma: String,
    pub f_eponymo_patros: String,
    pub f_onoma_patros: String,
    pub f_eponymo_mitros: String,
    pub f_onoma_mitros: String,
    pub f_topos_gennhshs: String,
    pub f_birthdate: String,
    pub f_sex: String,
    pub f_yphkoothta: String,
    pub f_typos_taytothtas: String,
    pub f_ar_taytothtas: String,
    pub f_ekdousa_arxh: String,
    pub f_date_ekdosis: String,
    pub f_date_ekdosis_lixi: String,
    pub f_res_permit_inst: String,
    pub f_res_permit_inst_type: String,
    pub f_res_permit_inst_ar: String ,
    pub f_res_permit_inst_lixi: String,
    pub f_res_permit_ap: String,
    pub f_res_permit_ap_type: String,
    pub f_res_permit_ap_ar: String,
    pub f_res_permit_ap_lixi: String,
    pub f_res_permit_visa: String,
    pub f_res_permit_visa_ar: String,
    pub f_res_permit_visa_from: String,
    pub f_res_permit_visa_to: String,
    pub f_marital_status: String,
    pub f_arithmos_teknon: String,
    pub f_afm: String,
    pub f_doy: String,
    pub f_amika: String,
    pub f_amka: String,
    pub f_code_anergias:String,
    pub f_ar_vivliou_anilikou: String,
    pub f_dieythinsi: String,
    pub f_kallikratis: String,
    pub f_tk: String,
    pub f_til: String,
    pub f_fax: String,
    pub f_email: String,
    pub f_epipedo_morfosis: String,
    pub f_professional_education: String,
    pub f_expertise_field: String,
    pub f_subject_area: String,
    pub f_subject_group: String,
    pub f_education_agency: String,
    pub f_education_date_from: String,
    pub f_education_date_to: String,
    pub f_duration: String,
    pub f_education_year: String,
    pub f_fl1: String,
    pub f_fl2: String,
    pub f_fl3: String,
    pub f_fl4: String,
    pub f_pc: String,
    pub f_pc_other: String,
    pub f_proslipsidate: String,
    pub f_proslipsitime: String,
    pub f_apoxwrisitime: String,
    pub f_orario: String,
    pub f_wresexternal: String,
    pub f_week_hours: String,
    pub f_orariodialeima: String,
    pub f_eidikothta: String,
    pub f_proipiresia: String,
    pub f_apodoxes: String,
    pub f_hour_apodoxes: String,
    pub f_protiergasia: String,
    pub f_sxeshapasxolisis: String,
    pub f_orismenou_apo: String,
    pub f_orismenou_ews: String,
    pub f_kathestosapasxolisis: String,
    pub f_xaraktirismos: String,
    pub f_special_case: String,
    pub f_apoalliperioxi: String,
    pub f_nationalityalli: String,
    pub f_kallikratisalli: String,
    pub f_responsible_position: String,
    pub f_working_time_digital_organization: String,
    pub f_full_employment_hours: String,
    pub f_week_days: String,
    pub f_euelikto_wrario_minutes: String,
    pub f_working_card: String,
    pub f_dialeimma_minutes: String,
    pub f_dialeimma_entos_wrariou: String,
    pub f_topothetisiepistoli: String,
    pub f_topothetisioaed: String,
    pub f_programaoaed: String,
    pub f_replaceprograma: String,
    pub f_replaceprograma_afm: String,
    pub f_replaceprograma_amka: String,
    pub f_epidomaoaed: String,
    pub f_epidoma_ypiresia_oaed: String,
    pub f_sk_protocol: String,
    pub f_sk_date: String,
    pub f_comments: String,
    pub f_eponymo_idiotitas: String,
    pub f_onoma_idiotitas: String,
    pub f_idiotita_idiotitas: String,
    pub f_dieythinsi_idiotitas: String,
    pub f_afm_idiotitas: String,
    pub f_afm_proswpoy: String,
    pub f_file: String,
    pub f_foreign_file: String,
    pub f_young_file: String,
}

